version: '3.9'

services:
  postgres:
    container_name: csharpTeste
    image: postgres:12
    ports: 
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_CONFIG_SESSION_EXPIRATION_TIME: "365"
      PGADMIN_MASTER_PASSWORD_REQUIRED: "false"
      PGADMIN_DEFAULT_EMAIL: neoapp@admin.com
      PGADMIN_DEFAULT_PASSWORD: masterkey123456
    ports:
      - 8085:80
  #    volumes:
  #    - ./pgadmin.json:/pgadmin4/servers.json:ro

networks:  
  external:
    name: web

volumes:
  pgdata:

